site_name: "Dynatrace Observability Lab: Grafana k6 Observability"
nav:
  - '1. About': index.md
  - '2. Getting Started': getting-started.md
  - '3. Run Demo': run-demo.md
  - '4. Cleanup': cleanup.md  
  - "5. What's Next?": whats-next.md
  - '6. Resources': resources.md
theme:
  name: material
markdown_extensions:
  - attr_list 
  - toc:
      permalink: '#'